### ISSUE TITLE
Definition of (first) match

### ISSUE THREAD

**Issue by gui11aume** [ezorita/seeq#16]
In case of a match with error on the first nucleotide, seeq favors deletions instead of mismatches. For instance `seeq -md1 GATCGATC <(echo "ttcATCGATCgg")` returns `ATCGATC`. However, the first match is `cATCGATC`.

**Comment by Arancheision** [comment]
That could be the reason why we only have deletions?? In any case it’s still weird that we would have only mismatches and not a single correct molecule... 

Enviado desde mi iPhone

**Comment by gui11aume** [comment]
@Arancheision this is very unlikely to be the explanation for the deletions observed in your run. We use seeq all the time and so far we have never noticed any case where it is "wrong". This case is very specific and applicable only when the first nucleotide of the pattern is a mismatch. I noticed it when analyzing the data of Albert (where the example is taken from actually).

**Comment by Arancheision** [comment]
Yep, I supposed so..

Enviado desde mi iPhone

**Comment by ezorita** [comment]
Hmm.. yes it's kinda tricky to define which is the right 'first' match... I
have to think again why I decided that the shortest match is always the
best option, but if you have other suggestions, please let me know.

Missatge de Arancheision <notifications@github.com> del dia dg., 3 de juny
2018 a les 20:28:

**Comment by gui11aume** [comment]
The fix seems to find the first match... which is not what I thought it would be. To continue with the initial example `seeq -md1 GATCGATC <(echo "ttgtATCGATCgg")` returns `gtATCGATC`. But `seeq -md1 GATCGATC <(echo "ttctATCGATCgg")` returns `tATCGATC`. Returning the first match does not make it less awkward because we now have introduced a sensitivity to the nucleotides before the pattern (especially in the case of 1 error).

I am not sure what is the best option. Returning the first match (longest extension of the reverse automaton) makes sense but it is not always intuitive. Alternatives are to allow Hamming distance instead of Levenshtein distance, or to return a match as long as the pattern (but I think that this definition does not make the match unique).
