### ISSUE TITLE
Found a bug using prefix option

### ISSUE THREAD

**Issue by Olja** [ezorita/seeq#6]
When matching this pattern CATGTTACAAATAAAGCAATAGCATCA to this sequences
ACCTCGTAAAAGCTATAGACTTGCATGTTACAAATAAAGCAATAGCTCGT
ACCTCGTAAAAGCTATAGACTTGCATGTTACAAATAAAGCAATAGCATCA
using -b option, the sequence is not trimmed correctly.

**Comment by gui11aume** [comment]
Here is a mini case to reproduce the bug (with -b -d3).
CGTATTGCGTGTGAGAAGGGCATGTTACAAATAAAGCAATAGCATCAGTA
ACCTCGTAAAAGCTATAGACTTGCATGTTACAAATAAAGCAATAGCTCGT
GGGATCAATGCATCCGNTAGCATGTTACAAATAAAGCAATAGNNNCACGC

**Comment by ezorita** [comment]
Corrected in commit f46e04d8192e7cb2a09e12a1d5bb979a356b9106.
